# Generated by Django 3.2.12 on 2022-02-19 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('cinemaId', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=200)),
                ('totalScreen', models.IntegerField()),
                ('city', models.TextField(max_length=200)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieId', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=200)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('duration', models.IntegerField()),
                ('releaseDate', models.DateField()),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Screens',
            fields=[
                ('hallId', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=200)),
                ('totalSeat', models.IntegerField()),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('cinemaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('showId', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('showTime', models.DateTimeField()),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('hallId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.screens')),
                ('movieId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
    ]
