# Generated by Django 3.2.12 on 2022-02-19 07:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20220219_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieId',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
